# Generated by Django 4.0.4 on 2022-05-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.user')),
                ('Role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20)),
            ],
        ),
    ]
